version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      BOT_TOKEN: "BOT_TOKEN"
      DB_CONNECTION_STRING: "Server=db;Port=5432;Database=finder;User Id=postgres;Password=finder;"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "finder"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "finder"
  web:
    ports:
      - "8080:80"
    depends_on:
      - db
    image: ghcr.io/jakeygilly/finderweb:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DISCORD_CLIENT_SECRET: "DISCORD_CLIENT_SECRET"
      DISCORD_CLIENT_ID: "DISCORD_CLIENT_ID"
      DISCORD_BOT_TOKEN: "DISCORD_BOT_TOKEN"
      DB_CONNECTION_STRING: "Server=db;Port=5432;Database=finder;User Id=postgres;Password=finder;"
      BOT_OWNERS: "USER_ID,USER_ID"
